---
title: "R_data_science_Introduction"
author: "ML"
date: "12/01/2019"
output: html_document
---

My exercise solutions for the book R for Data Science, by Hadley Wickham and Garret Grolemund (Wickham and Grolemund 2017).     
Original exercise solutions book (called " R for Data Science: Exercise Solutions) can be found here:
https://jrnold.github.io/r4ds-exercise-solutions/introduction.html   

# Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

install.packages("tidyverse")
library(tidyverse)
devtools::session_info(c("tidyverse"))

#install.packages(c("nycflights13", "gapminder", "Lahman"))
```


```{r mpg dataset and Basic ggplot}
?mpg
mpg ## A tibble: 234 x 11
str(mpg)

#plot fuel effciency vs. engine size:
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))
#plot fuel effciency vs. number of cylinders:
ggplot(data = mpg) +
  geom_point(mapping = aes(x = cyl, y = hwy))
#plot car class vs. drive type:
ggplot(data = mpg) +
  geom_point(mapping = aes(x = drv, y = class))
# with class as color
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
# with class as transparency
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
# with class as shapes
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
# with all ponts blue (outside aes)
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

```{r Exercises p12}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = drv, y = hwy, color = displ))
# with class as shapes and colors
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, shape = drv, color = drv))
# with cutoff for colour change
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy,color = displ < 5))

# cat vs. cat variable frequency plots:
ggplot(mpg, aes(x = class, y = drv)) +
  geom_count()
mpg %>%
  count(class, drv) %>%
  ggplot(aes(x = class, y = drv)) +
  geom_tile(mapping = aes(fill = n))
mpg %>%
  count(class, drv) %>%
  complete(class, drv, fill = list(n = 0L)) %>%
  ggplot(aes(x = class, y = drv)) +
  geom_tile(mapping = aes(fill = n))
```

```{r mpg dataset and ggplot Facets}
# with facets by one categorical variable
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(~ class, nrow = 2)
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)

# with facets by two categorical variables
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ cyl)
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(class ~ cyl)
```

```{r Exercises p12}
#1. with facets by one categorical variable
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(~ displ, nrow = 2)
#2. with trwo cat variables plot
ggplot(data = mpg) +
  geom_point(mapping = aes(x = drv, y = cyl))
#3. split horizonatally or vertically by one cat variable
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ .)
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)
```

```{r mpg dataset and Geometric Objects}
# point geom
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))
# smooth geom
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
# smooth geom with line types for subsets
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))

# smooth geom with line types and colors for subsets
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, color = drv),
  show.legend = FALSE)

# display multiple geoms in the same plot
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))

# two geoms as above, but using a single global mapping
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth()

# combination of global and local mappings to display different aesthetics in different layers
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = class)) +
  geom_smooth()

# specify different data for each layer
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = class)) +
  geom_smooth(
  data = filter(mpg, class == "subcompact"),
  se = FALSE
  )
```

```{r Exercises p20}
#2. without fitting error shade
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) +
  geom_point() +
  geom_smooth(se = FALSE)
#5. two alt ways to spacify same plot
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth()
ggplot() +
  geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy)
  )
#6. recreate plots
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy), se = FALSE)
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv), se = FALSE)
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, group = drv, color = drv)) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv, color = drv), se = FALSE)
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, group = drv, color = drv)) +
  geom_smooth(mapping = aes(x = displ, y = hwy), se = FALSE)
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, group = drv, color = drv)) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv, linetype = drv), se = FALSE)
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, group = drv, fill = drv), shape = 21, color = "white", size=2)
```

```{r diamonds dataset and Statistical Transformations}
#histograms of counts by diamond cut type
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut))
#equivalent to
ggplot(data = diamonds) +
  stat_count(mapping = aes(x = cut))

#using preset values (identity) ina histogram
demo <- tribble(
  ~a, ~b,
  "bar_1", 20,
  "bar_2", 30,
  "bar_3", 40
  )
ggplot(data = demo) +
  geom_bar(
  mapping = aes(x = a, y = b), stat = "identity"
  )

#display a bar chart of proportion, rather than count:
ggplot(data = diamonds) +
  geom_bar(
  mapping = aes(x = cut, y = ..prop.., group = 1)
  )

#display computed summaries for depths by cut type:
ggplot(data = diamonds) +
  stat_summary(
  mapping = aes(x = cut, y = depth),
  fun.ymin = min,
  fun.ymax = max,
  fun.y = median
  )
```


```{r Exercises p26}
#1. pointrange def geom for stat_summary
ggplot(data = diamonds) +
  geom_pointrange(
    mapping = aes(x = cut, y = depth),
    stat = "summary",
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
#.3 geom - stats pairs:
# geom_bar() 	      stat_count()
# geom_bin2d() 	    stat_bin_2d()
# geom_boxplot() 	  stat_boxplot()
# geom_contour() 	  stat_contour()
# geom_count() 	    stat_sum()
# geom_density() 	  stat_density()
# geom_density_2d() stat_density_2d()
# geom_hex() 	      stat_hex()
# geom_freqpoly() 	stat_bin()
# geom_histogram() 	stat_bin()
# geom_qq_line() 	  stat_qq_line()
# geom_qq() 	      stat_qq()
# geom_quantile() 	stat_quantile()
# geom_smooth() 	  stat_smooth()
# geom_violin() 	  stat_violin()
# geom_sf() 	      stat_sf()

#4. stat_smooth computes values:
#y - predicted value
#ymin - lower pointwise confidence interval around the mean
#ymax - upper pointwise confidence interval around the mean
#se - standard error

#5.stacked bar charts
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = color, y = ..prop.., group = color))
```
m
```{r diamonds dataset and Position Adjustments}
# various arrangements for barplots:
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, color = cut))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = cut))

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity))

ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) +
  geom_bar(alpha = 1/5, position = "identity")

ggplot(data = diamonds, mapping = aes(x = cut, color = clarity)) +
  geom_bar(fill = NA, position = "identity")

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")

# jitter and aplpha for scatterplots:
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy), alpha = 1/5, position = "jitter")
# equivalent to:
ggplot(data = mpg) +
  geom_jitter(mapping = aes(x = displ, y = hwy), alpha = 1/5)
```

```{r Exercises p31}
# 1. resolve overlapping points
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_jitter(alpha = 1/5)
# 2. width and width
# 3. geom_count() sizes the points relative to the number of observations
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_count(alpha = 1/5)
# 4. default position for geom_boxplot() is "dodge2", which is a shortcut for position_dodge2
ggplot(data = mpg, aes(x = cyl, y = hwy, colour = class)) +
  geom_boxplot()
```

```{r mpg and diamonds dataset and Coordinate Systems}
# flip coordinates:
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
  geom_boxplot()
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
  geom_boxplot() +
  coord_flip()

# set the coordinate aspect ratio:
library(maps)
nz <- map_data("nz")
ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", color = "black")
ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", color = "black") +
  coord_quickmap()

# with polar coordinates:
bar <- ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = cut), show.legend = FALSE, width = 1) +
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)
bar + coord_flip()
bar + coord_polar()
```

```{r Exercises p33}
# 1. pie charts
ggplot(mpg, aes(x = factor(1), fill = drv)) +
  geom_bar(width = 1) +
  coord_polar(theta = "y")

ggplot(mpg, aes(x = factor(1), fill = drv)) +
  geom_bar(width = 1) +
  coord_polar()

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut, fill = clarity)) +
  coord_polar()

# 2. labs() adds various labels

# 3. coord_quickmap() simplified Earth projection ignoring the curvature of Earth and coord_map() project the three-dimensional Earth onto a two-dimensional plane using theMercator projection

# 4. compare the highway and city mileage
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point() +
  geom_abline() +
  coord_fixed() #fixes line at 45 degrees
```
